### ISSUE TITLE
sassResources wrong type error

### ISSUE THREAD

**Issue by mdentinho** [shakacode/sass-resources-loader#12]
Hey guys,

I've been trying to implement this loader in a project, but it keeps throwing this error:

```
Module build failed: Error:                                                                  
      Looks like sassResources property has wrong type.                                      
      Make sure it's String or Array of Strings.                                             

    at Object.module.exports (~/...//node_modules/sass-resources-loader/lib/loader.js:58:18)
```

But sassResources is an Array of strings:

```
  sassResources: [
    '../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss',
    '../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_mixins.scss'
  ]
```

I'm also using [bootstrap-loader](https://github.com/shakacode/bootstrap-loader/) (v2.0.0-beta.3), if that matters, and I'm trying to make bootstrap's variables and mixings available in my styles.

Is there something I'm missing?

Thanks

**Comment by justin808** [comment]
@mdentinho We just fixed a few bugs in bootstrap-loader. try beta.5

**Comment by mdentinho** [comment]
@justin808 Unfortunately, it didn't solve the problem. The errors persist. :(

**Comment by smitray** [comment]
@justin808 , Tried with beta 10, 5, 8 and exports.1, didn't work. Same issue. Between I'm trying to implement it in angularclass webpack starter and yeah one more issue, I tried to implement Bootstrap4 and failed (config file kept throwing error and there is an error with 'UMD' path). @mdentinho if this helps, I imported the variable file and that works.

**Comment by justin808** [comment]
Are you two using webpack v2 or v1?

bootstrap-loader v2 is ONLY for webpack v2

**Comment by smitray** [comment]
@justin808, I'm using webpack 2.1.0-beta.21

**Comment by justin808** [comment]
@mdentinho @smitray I'll need you two to help debug this issue.

**Comment by justin808** [comment]
@smitray @albertomr86 @mdentinho Please try the latest bootstrap-loader. I just released a new version today. We might have a problem with this loader with webpack v2. Maybe that's the difference. We had to create a different version of bootstrap-loader for webpack v2.

**Comment by smitray** [comment]
@justin808 not much of a help :(
![screenshot_2016-09-10_14-31-42](https://cloud.githubusercontent.com/assets/4408550/18409530/f1caac8a-7766-11e6-9ce3-e6a0db159de6.png)

**Comment by justin808** [comment]
@smitray I recommend that you download the source code locally for both the bootstrap-loader and the sass-resources-loader and put in some print statements to help us debug this.

I'd love to help, but I can't right now. Your help is a great asset to the community.

**Comment by tutts** [comment]
Hey guys, having the same issue here. I'm not using bootstrap-loader, on webpack 1.13.2. let me know if theres something I can do to debug :)

**Comment by justin808** [comment]
@smitray, @albertomr86 @mdentinho: 
Have you tried out the tips here on debugging: https://forum.shakacode.com/t/debugging-nodejs-and-webpack-loaders/142 ?

@alexfedoseev and I are slammed right. The best we can do is to review a well done PR.

**Comment by samfrach** [comment]
Hello,

I confirm the issue.

What ever I pass, I get an empty array back from this function in parseResources.js
It seems glob is returning [] .... 
locations is for example a string 'app/style/utils.scss' or an array ['', ''] of 2 files...
I've tried with very simple string '*.scss' ....
 
`exports.default = function (locations) {
  if (typeof locations === 'string') {
    _logger2.default.debug('sassResources is String:', true);
    return _glob2.default.sync(locations);
  }

  if ((0, _isArrayOfStrings2.default)(locations)) {
    _logger2.default.debug('sassResources is Array of Strings:', true);
    var paths = locations.map(function (file) {
      return _glob2.default.sync(file);
    });
    return (0, _flattenArray2.default)(paths);
  }

  return [];
};`


what to do ? 

thank you

PS: I have using it with the webpack angular2 project from angularclass.

**Comment by smitray** [comment]
@justin808 finally I got this working. Actually, the issue is with the file path. As  @samfrach mentioned it's because of the glob.
People who are using AngularClass starter, need to put address the file path from the root folder. Like I kept my variables.scss file inside config folder so I had to mention the path as './config/variables.scss', even though the webpack common config file is inside the config folder. Also, you need to use the .bootstraprc file, I don't know why but it didn't work without this file.

**Comment by samfrach** [comment]
thank you, I'm going to try it.
@smitray maybe you could help on my issue : https://github.com/preboot/angular2-webpack/issues/186

**Comment by justin808** [comment]
@smitray @samfrach If either of you could do a doc PR, that would be great for the community.

**Comment by smitray** [comment]
@samfrach I just went through your issue and I think you can sass-resources-loader. This works really fine. You don't even need to import your lib in your individual scss files. Anyway, I'm not sure which framework you're using, but I tried with TWB 3. You can follow the instructions mentioned in the following link if you're using TWB (Please note: there are issues with TWB4 rc file, you may get few errors).

https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery)

----
Once it's done, install sass-resources-loader, edit your webpack common config file. Here it's the tricky part. In my case, I needed the variables.scss file to be easily accessible and so I made a copy of it and put it in config folder and the mixin.scss file is still in the node_modules folder. Now my 

`sassResources: ['./config/variables.scss', 'node_modules/path/to/your/mixin'],`

That's pretty much it.

@justin808 I'll try with F6 and other frameworks, over this weekend and will update here.

**Comment by samfrach** [comment]
Using the webpack-starter project from AngularClass (https://github.com/AngularClass/angular2-webpack-starter), I have all my ng2 components splitted into a .ts, a .html and a .scss file. 
In order to use mixins and constants in my scss files, I don't want to add in all of them an "@import '../.././../utils' " (note the relative path constraint..)
Since the sass-resources-loader is able to act as if I had included this @import line, I'm happy to use it.
I've had difficulties to find the correct syntax on how to use it.


Finally, in the webpack.config.js file, I have : 

added : 
   config.sassResources = ['./src/app/style/utils.scss'];
AND changed this line : 
    {test: /\.scss$/, exclude: root('src', 'style'), loader: 'raw!postcss!sass!sass-resources'},


note that my file structure is : 
<root> webpack.config.js / package.json / etc...
<src>\ * <-- all my ts/html/scss files
<node_modules>...

**Comment by prosanes** [comment]
Just to let know, that I had this error when using a path like `../path/to/resource`.
But once i used `./../path/to/resource` I had no error.

**Comment by AppliedApathy** [comment]
Had the same issue. If it does not find anything at given paths, it will complain about "sassResources wrong type". In my case I used paths relative to webpack config context, but actual lookup directory was the directory, node script was started from.

**Comment by IMalyugin** [comment]
In my case this issue is caused by sass-resources-loader ignoring webpack.options.context that allows using project relative paths in webpack.

Fixed by passing webpack.options.context in parseResourses.default, followed by doing
_path.resolve(context, location) in parseResolve.js (for every file given)

**Comment by justin808** [comment]
@IMalyugin @AppliedApathy @prosanes @samfrach @smitray Should we have a doc change for this?

**Comment by prosanes** [comment]
Seems like a good idea to me.

**Comment by justin808** [comment]
@IMalyugin @AppliedApathy @prosanes @samfrach @smitray Can any of you submit a PR for the doc change?

I pushed up a beta: 1.2.0-beta.1 for webpack v2 support: https://github.com/shakacode/sass-resources-loader/pull/16

**Comment by iantanwx** [comment]
If this is still broken for you, use an absolute path, like so:

```
...
options: {
  resources: [ path.resolve(__dirname, './resources.scss') ]
}
...
```

`glob` can't deal with relative paths, which is used to resolve paths in this loader.

**Comment by alexfedoseev** [comment]
Should be fixed in `1.2.0`. 
Note about missing `context` also added to README.
If anyone still experiences problems, please, create new issue as this one became quite messy.

**Comment by warent** [comment]
FWIW: I was just receiving this error:

```
Module build failed: Error:
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
```

Even though options.resources was a String (also tried with a single index array). The problem turned out to be a typo in my path (wrong file name). Please consider updating the error text as it can be quite misleading!

**Comment by justin808** [comment]
@warent Can you please reproduce your issue and submit a PR for this improvement. That's a good idea.
